<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.7.4 on win32)" generated="20191010 13:24:51.721" rpa="false">
<suite id="s1" name="RegistrationTC" source="D:\SeleniumPython\TestBase\RegistrationTC.robot">
<test id="s1-t1" name="TC1 User Registration">
<kw name="No Operation" library="BuiltIn">
<doc>Does absolutely nothing.</doc>
<status status="NOT_RUN" starttime="20191010 13:24:51.932" endtime="20191010 13:24:51.932"></status>
</kw>
<status status="PASS" starttime="20191010 13:24:51.931" endtime="20191010 13:24:51.932" critical="yes"></status>
</test>
<status status="PASS" starttime="20191010 13:24:51.723" endtime="20191010 13:24:51.932"></status>
</suite>
<statistics>
<total>
<stat pass="1" fail="0">Critical Tests</stat>
<stat pass="1" fail="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="1" fail="0" id="s1" name="RegistrationTC">RegistrationTC</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20191010 13:24:51.716" level="ERROR">Error in file 'D:\SeleniumPython\TestBase\RegistrationTC.robot': Setting 'Documentation' used multiple times.</msg>
<msg timestamp="20191010 13:24:51.925" level="ERROR">Error in file 'D:\SeleniumPython\Resource\Registration.robot': Setting 'Documentation' used multiple times.</msg>
</errors>
</robot>
